### ISSUE TITLE
Releases, Naming & Semver

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/lslint#100]
Sorry, I'm kind of lost with the latest updates:

* You're tagging the same commit with three different version tags.
* Newer tags in time are older according to SemVer, though.
* Looking at the following, I'm not even sure what is what:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/13032004/76475050-febe9500-63fd-11ea-8ae5-f88e7dab33a9.png">

**Comment by buildersbrewery** [comment]
What should we test? Which binary is for what?

**Comment by Makopo** [comment]
all of them was deprecated, closing.
