### ISSUE TITLE
Request: Support for preprocessor includes

### ISSUE THREAD

**Issue by zontreck** [Makopo/lslint#101]
Please add support for preprocessor includes. They may not be a core LSL feature but third party viewers have adopted this useful feature.

**Comment by Sei-Lisa** [comment]
It doesn't make sense to add includes without adding everything else a preprocessor can do. And a preprocessor is out of scope for this project.

Instead, grab a preprocessor and use it together with lslint. This project already supports filtering the preprocessor output, and in my opinion that's exactly the extent that it should cover.

**Comment by zontreck** [comment]
if you have a suggestion for a CLI Preprocessor, then my ears are open on that. But otherwise it would still be a good idea in my opinion to add the ability to parse preprocessor includes, and other preprocessor commands.

**Comment by Sei-Lisa** [comment]
Check mcpp, http://mcpp.sourceforge.net/ . If you prefer Python, there's also PCPP, https://github.com/ned14/pcpp .

**Comment by buildersbrewery** [comment]
@zontreck You want to use:

- an older `Build 3xxx` release of: <https://www.sublimetext.com/3>
- an older `version 3.x.x` release of: <https://github.com/SublimeLinter/SublimeLinter/>
- <https://github.com/XenHat/SublimeLinter-contrib-lslint/>
