### ISSUE TITLE
update lslint with new data from kwdb

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/lslint#103]
Hi,

could you update lslint with new data from kwdb?

Thanks

**Comment by buildersbrewery** [comment]
ping @Makopo

**Comment by Sei-Lisa** [comment]
You can always use an external builtins.txt file with option `-b`. Grab the latest version from here: https://github.com/Sei-Lisa/kwdb/raw/master/outputs/builtins.txt

**Comment by Sei-Lisa** [comment]
You can always use an external builtins.txt file with option `-b`. Grab the latest version from here: https://github.com/Sei-Lisa/kwdb/raw/master/outputs/builtins.txt

**Comment by Sei-Lisa** [comment]
This will be solved in the next release. https://github.com/Makopo/lslint/pull/104

------- Original Message -------
