### ISSUE TITLE
Error when using special preprocessor-provided constants

### ISSUE THREAD

**Issue by XenHat** [Makopo/lslint#107]
Thanks for the updated binaries, I can script again!

I am having issues when using some special constants provided by the LSL Preprocessor, such as `__AGENTID__`:
![image](https://user-images.githubusercontent.com/980408/222276587-ab30c785-4567-4b3b-9af0-4f55e54ebe05.png)

Would it be possible to treat them properly?

The few constants added by the preprocessor are the following:

- [ ] `__FILE__` - the full path to the script as it would appear in the include cache. The top script only uses its name.
- [ ] `__LINE__` - the line of the current script where it is expanded; this starts at line 0
- [ ] `__SHORTFILE__` - the name of the current script without full file path
- [ ] `__AGENTID__` - a string-encapsulated version of the agent's key who compiles the script
- [ ] `__AGENTKEY__` - same as above, legacy version
- [ ] `__AGENTIDRAW__` - a nonstring-encapsulated version of the agent's key who compiles the script
- [ ] `__AGENTNAME__` - a string-encapsulated version of the agent's full name who compiles the script
- [ ] `__ASSETID__` - a string-encapsulated version of the assetid of the current script; may return “NOT IN WORLD” or a nonstring-encapsulated null key in rare circumstances

Source:  [#preprocessor_commands_and_macros]( https://wiki.firestormviewer.org/fs_preprocessor#preprocessor_commands_and_macros)

**Comment by Sei-Lisa** [comment]
What preprocessor are you using and how do you expect it to receive e.g. your agent UUID?

The optimizer has options to set these macros; you can run the preprocessor through it, setting the values via the command line, and use the --preshow option to make it stop after preprocessing.

**Comment by XenHat** [comment]
I am using the same setup I have been using this whole time: Sublime Text, SublimeLinter3, my plugin and mcpp :)

**Comment by Sei-Lisa** [comment]
The other question remains, how do you expect it to receive e.g. your agent UUID?

`__FILE__` and `__LINE__` are standard and mcpp already makes those work. The rest are Firestorm-exclusive.

`__SHORTFILE__` needs to be generated from the file somehow. The Linux utility `basename` could do that.

So, you could create a bash file like this:

```bash
#!/bin/bash
my_uuid="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
my_name="xxxxx"
mcpp -D__AGENTID__=\""$my_uuid"\" -D__AGENTKEY__=\""$my_uuid"\" -D__AGENTIDRAW__="$my_uuid" -D__AGENTNAME__="$my_name" -D__ASSETID__="NOT IN WORLD" -D__SHORTFILE__="$(basename "$1")" "$1" -o "$2"
```

and run it instead of running mcpp directly, with the first argument being the input file and the second argument the output file. Add any other mcpp options you're using where appropriate.

**Comment by XenHat** [comment]
Ooh clever. I didn't think of that. I suppose that is a better option than
making the linter ignore it, too. I'll add some code to my linter to see if
I can work around this in a fairly easy to use way.
