### ISSUE TITLE
win x64 executable

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/lslint#3]
@Makopo Maybe you could merge @XenHat 's changes from [`Ociidii-Works/lslint`](https://github.com/Ociidii-Works/lslint) into your repo so there's a win x64 executable available here, too?

**Comment by XenHat** [comment]
Oh lord, my commit history is pretty messy, that'd be embarrassing. 😨

**Comment by buildersbrewery** [comment]
Just a suggestion from my side, whatever works...

**Comment by XenHat** [comment]
Oh, I don't mind. I'm just worried that @Makopo might not like the intrusive changes.

**Comment by XenHat** [comment]
There, I re-implemented the fixes in a less intrusive way.

**Comment by Makopo** [comment]
@XenHat I appreciate your pull request, since I believe who developed original a long ago was you.

**Comment by XenHat** [comment]
I'm 99.999% confident I am not the original author of lslint. I will create a pull request nonetheless.

**Comment by Makopo** [comment]
Oh, I see. I guessed from your name that you were from w-hat. Anyway I am not good about engine coding so I'll appreciate your request 👍 Since I am away for Tokyo tomorrow so I'll look at pull request this weekend.

**Comment by buildersbrewery** [comment]
旅行楽しんで下さい。

**Comment by Makopo** [comment]
merged.
