### ISSUE TITLE
Unrecognized constants

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/lslint#5]
```text
SIT_INVALID_AGENT
SIT_INVALID_LINK
SIT_INVALID_OBJECT
SIT_NOT_EXPERIENCE
SIT_NO_ACCESS
SIT_NO_EXPERIENCE_PERMISSION
SIT_NO_SIT_TARGET
```

tested with Makopo/lslint@68879c8.

/cc @XenHat

**Comment by Makopo** [comment]
Since  there is no such entry in kwdb database.
You might want to request this to them if you consider this as a issue.

**Comment by buildersbrewery** [comment]
@Sei-Lisa

**Comment by Sei-Lisa** [comment]
Fixed in kwdb. For some reason I'm not receiving emails, I'll look into that. But thanks for the heads-up.

**Comment by buildersbrewery** [comment]
> @Sei-Lisa
> 
> * <https://github.com/settings/emails>
> * <https://github.com/settings/notifications>
>   * <https://github.com/notifications>
>   * <https://github.com/watching>
