### ISSUE TITLE
Unexpected error with fs preprocessor examples

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/lslint#71]
Using [`lslint v1.0.9` with `mcpp v2.7.2`](https://github.com/XenHat/SublimeLinter-contrib-lslint/blob/6674409/linter.py) with the [fs preprocessor](http://wiki.phoenixviewer.com/fs_preprocessor) example scripts:

![image](https://user-images.githubusercontent.com/13032004/34720881-bf9dc82e-f540-11e7-9b6d-2a48ceb60494.png)

**Comment by Sei-Lisa** [comment]
The include files can't be linted; only the main file can. lslint always expects a complete program, not a fragment that can be included as part of another script.
