### ISSUE TITLE
Win64 binaries?

### ISSUE THREAD

**Issue by XenHat** [Makopo/lslint#99]
[lslint.zip](https://github.com/Makopo/lslint/files/4183295/lslint.zip)

I have sucessfully compiled new win64 binaries. Should the build system be fixed?

**Comment by Makopo** [comment]
I was trying to build on travis-ci (and discontinue Windows XP build). Fixes are welcomed.

**Comment by Makopo** [comment]
Thank you for offering.
My new local environment can now successfully compile win 64 binaries :)
